# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_meta": "core.ipynb",
         "meta_list": "core.ipynb",
         "find_dupe": "core.ipynb",
         "chk_dupe_title": "core.ipynb",
         "chk_desc": "core.ipynb",
         "chk_img": "core.ipynb",
         "chk_len": "core.ipynb",
         "chk_desc_len": "core.ipynb"}

modules = ["core.py"]

doc_url = "https://outerbounds.github.io/mdseo/"

git_url = "https://github.com/outerbounds/mdseo/tree/master/"

def custom_doc_links(name): return None
